// request actions
export const UPDATE_AUTOCOMPLETE_QUERY = 'UPDATE_AUTOCOMPLETE_QUERY';
export const UPDATE_DETAILS_ID = 'UPDATE_DETAILS_ID';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const SELECT_REFINEMENT = 'SELECT_REFINEMENT';
export const DESELECT_REFINEMENT = 'DESELECT_REFINEMENT';
export const SELECT_COLLECTION = 'SELECT_COLLECTION';
export const SELECT_SORT = 'UPDATE_SORTS';
export const UPDATE_PAGE_SIZE = 'UPDATE_PAGE_SIZE';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';

// response actions
export const RECEIVE_MORE_REFINEMENTS = 'RECEIVE_MORE_REFINEMENTS';
export const RECEIVE_AUTOCOMPLETE_SUGGESTIONS = 'RECEIVE_AUTOCOMPLETE_SUGGESTIONS';
export const RECEIVE_AUTOCOMPLETE_PRODUCTS = 'RECEIVE_AUTOCOMPLETE_PRODUCTS';
export const RECEIVE_DETAILS_PRODUCT = 'RECEIVE_DETAILS_PRODUCT';
export const RECEIVE_QUERY = 'RECEIVE_QUERY';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_COLLECTION_COUNT = 'RECEIVE_COLLECTION_COUNT';
export const RECEIVE_NAVIGATIONS = 'RECEIVE_NAVIGATIONS';
export const RECEIVE_PAGE = 'RECEIVE_PAGE';
export const RECEIVE_RECORD_COUNT = 'RECEIVE_RECORD_COUNT';
export const RECEIVE_TEMPLATE = 'RECEIVE_TEMPLATE';
export const RECEIVE_REDIRECT = 'RECEIVE_REDIRECT';

// request status
export const SO_FETCHING = 'SO_FETCHING';

// ui
export const CREATE_COMPONENT_STATE = 'CREATE_COMPONENT_STATE';
export const REMOVE_COMPONENT_STATE = 'REMOVE_COMPONENT_STATE';
